name: CI workflow

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docker-compose stack
        run: docker-compose -f docker-compose.yml --env-file ./src/.env up -d
  test:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docker-compose stack
        run: docker compose -f docker-compose.yml --env-file ./src/.env up -d
      - name: Test with pytest
        run: docker compose exec api python -m pytest -v
